/**
 * List of image paths to be cached
 * @type {Array<string>}
 */
let imageCacheData = [
  // Game-specific images
  "./img/Charakters/1%20Biker/Biker_idle/1.png",
  "./img/Charakters/1%20Biker/Biker_idle/2.png",
  "./img/Charakters/1%20Biker/Biker_idle/3.png",
  "./img/Charakters/1%20Biker/Biker_idle/4.png",
  "./img/Charakters/1%20Biker/Biker_run/1.png",
  "./img/Charakters/1%20Biker/Biker_run/2.png",
  "./img/Charakters/1%20Biker/Biker_run/3.png",
  "./img/Charakters/1%20Biker/Biker_run/4.png",
  "./img/Charakters/1%20Biker/Biker_run/5.png",
  "./img/Charakters/1%20Biker/Biker_run/6.png",
  "./img/Charakters/1%20Biker/Biker_jump/1.png",
  "./img/Charakters/1%20Biker/Biker_jump/2.png",
  "./img/Charakters/1%20Biker/Biker_jump/3.png",
  "./img/Charakters/1%20Biker/Biker_jump/4.png",
  "./img/Charakters/1%20Biker/Biker_death/1.png",
  "./img/Charakters/1%20Biker/Biker_death/2.png",
  "./img/Charakters/1%20Biker/Biker_death/3.png",
  "./img/Charakters/1%20Biker/Biker_death/4.png",
  "./img/Charakters/1%20Biker/Biker_death/5.png",
  "./img/Charakters/1%20Biker/Biker_death/6.png",
  "./img/Charakters/1%20Biker/Biker_hurt/1.png",
  "./img/Charakters/1%20Biker/Biker_hurt/2.png",

  // Background images
  "./img/Background/city 1/1.png",
  "./img/Background/city 1/2.png",
  "./img/Background/city 1/3.png",
  "./img/Background/city 1/4.png",
  "./img/Background/city 1/5.png",
  "./img/Background/city 1/6.png",
  "./img/Background/city 1/7.png",
  "./img/Background/city 1/8.png",
  "./img/Background/city 1/9.png",

  "./img/Background/city 2/1.png",
  "./img/Background/city 2/2.png",
  "./img/Background/city 2/3.png",
  "./img/Background/city 2/4.png",
  "./img/Background/city 2/5.png",
  "./img/Background/city 2/6.png",
  "./img/Background/city 2/7.png",
  "./img/Background/city 2/8.png",
  "./img/Background/city 2/9.png",

  "./img/Background/city 3/1.png",
  "./img/Background/city 3/2.png",
  "./img/Background/city 3/3.png",
  "./img/Background/city 3/4.png",
  "./img/Background/city 3/5.png",
  "./img/Background/city 3/6.png",
  "./img/Background/city 3/7.png",

  // Enemies
  "./img/Enemies/1/Walk/1.png",
  "./img/Enemies/1/Walk/2.png",
  "./img/Enemies/1/Walk/3.png",
  "./img/Enemies/1/Walk/4.png",
  "./img/Enemies/1/Hurt/1.png",
  "./img/Enemies/1/Hurt/2.png",
  "./img/Enemies/1/Death/1.png",
  "./img/Enemies/1/Death/2.png",
  "./img/Enemies/1/Death/3.png",
  "./img/Enemies/1/Death/4.png",
  "./img/Enemies/1/Death/5.png",
  "./img/Enemies/1/Death/6.png",

  "./img/Enemies/2/Walk/1.png",
  "./img/Enemies/2/Walk/2.png",
  "./img/Enemies/2/Walk/3.png",
  "./img/Enemies/2/Walk/4.png",
  "./img/Enemies/2/Walk/5.png",
  "./img/Enemies/2/Walk/6.png",
  "./img/Enemies/2/Hurt/1.png",
  "./img/Enemies/2/Hurt/2.png",
  "./img/Enemies/2/Death/1.png",
  "./img/Enemies/2/Death/2.png",
  "./img/Enemies/2/Death/3.png",
  "./img/Enemies/2/Death/4.png",
  "./img/Enemies/2/Death/5.png",
  "./img/Enemies/2/Death/6.png",
  "./img/Enemies/2/Idle/1.png",

  "./img/Enemies/3/Projectile.png",

  // Other game elements
  "./img/Crystals/4.png",
  "./img/GUI/2 Bars/EnergyBar1.png",
  "./img/GUI/2 Bars/EnergyBar2.png",
  "./img/GUI/2 Bars/EnergyBar3.png",
  "./img/GUI/2 Bars/EnergyBar4.png",
  "./img/GUI/2 Bars/EnergyBar5.png",
  "./img/GUI/2 Bars/EnergyBar6.png",
  "./img/GUI/2 Bars/EnergyBar7.png",
  "./img/GUI/2 Bars/EnergyBar8.png",
  "./img/favicon.png",
  "./img/GUI/8 Cursors/1.png",
];
